app:
  id: 1000130002
# set apollo meta server address, adjust to actual address if necessary
#apollo:
#  meta: http://10.19.83.64:8080/
#  bootstrap:
#      enabled: true
#      namespaces: application
# 服务器配置
server:
  port: 30002
# Spring相关配置
spring:
  application:
    name: ihrm-system
  boot:
    admin:
      client:
        url: http://10.19.83.64:8769
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.19.83.64:13306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password:
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true  #设置开启热部署
eureka:
  client:
    service-url:
      defaultZone: http://10.19.83.64:8761/eureka/,http://10.19.83.64:8762/eureka/
  instance:
    prefer-ip-address: true
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
