###---------所有配置已由apollo接管---------###
app:
  id: 1000031000
# set apollo meta server address, adjust to actual address if necessary
apollo:
  meta: http://10.19.83.64:8861
  bootstrap:
    enabled: true
    namespaces: application