# Spring相关配置
spring:
  application:
    name: server-registry-eureka
  profiles:
    active: peer1
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  client:
    # 是否将自己注册到eureka
     register-with-eureka: false
    # 是否从eureka中获取注册列表
     fetch-registry: false
    # 服务连接地址
  service-url:
    defaultZone: http://10.19.83.64:8761/eureka/,http://10.19.83.64:8762/eureka/
  instance:
    # 服务列表中显示IP地址
    prefer-ip-address: true
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 60000
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  client:
    # 是否将自己注册到eureka
     register-with-eureka: false
    # 是否从eureka中获取注册列表
     fetch-registry: false
    # 服务连接地址
  service-url:
    defaultZone: http://10.19.83.64:8761/eureka/,http://10.19.83.64:8762/eureka/
  instance:
    # 服务列表中显示IP地址
    prefer-ip-address: true
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 60000