package com.fbc.ihrm.entity.company;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * @TableName co_company
 */
@Entity
@Table(name="co_company")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Company implements Serializable {
    /**
     * ID
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    @Id
    private String id;

    /**
     * 公司名称
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String name;

    /**
     * 企业登录账号ID
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String managerId;

    /**
     * 当前版本
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String version;

    /**
     * 续期时间
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private Date renewalDate;

    /**
     * 到期时间
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private Date expirationDate;

    /**
     * 公司地区
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String companyArea;

    /**
     * 公司地址
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String companyAddress;

    /**
     * 营业执照-图片ID
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String businessLicenseId;

    /**
     * 法人代表
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String legalRepresentative;

    /**
     * 公司电话
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String companyPhone;

    /**
     * 邮箱
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String mailbox;

    /**
     * 公司规模
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String companySize;

    /**
     * 所属行业
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String industry;

    /**
     * 备注
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String remarks;

    /**
     * 审核状态
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private String auditState;

    /**
     * 状态
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private Integer state;

    /**
     * 当前余额
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private Double balance;

    /**
     * 创建时间
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table co_company
     *
     * @mbg.generated Thu Feb 04 10:02:19 CST 2021
     */
    private static final long serialVersionUID = 1L;
}