spring:
  application:
    name: admin-client
  boot:
      admin:
        client:
          url: http://10.19.83.64:8769
# 注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://10.19.83.64:8761/eureka/,http://10.19.83.64:8762/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 30001
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS