spring:
  application:
    name: spring-boot-admin
server:
  port: 8769
# 注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://10.19.83.64:8761/eureka/,http://10.19.83.64:8762/eureka/
  instance:
    prefer-ip-address: true
#actuator暴露所有信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@